### ISSUE TITLE
Common sources

### ISSUE THREAD

**Issue by JeanMax** [jon-finkel/corewar#1]
https://github.com/jon-finkel/corewar/blob/244ac2fecf0e35317391ecc01102deb880b09e74/include/corewar.h#L20

Yo!

J'ai fait un swap dword aussi:
https://github.com/jon-finkel/corewar/blob/master/src/asm/encoder/write_cor.c#L25

On pourrait mettre en commun les fonctions utilitaires pour l'encodage/decodage

**Comment by Freccia** [comment]
Oui clairement! Je vais regarder ton code cet aprem, puis on fait un point a 42, d'acc?
