### ISSUE TITLE
Ncurses: ajouter fonction pour mettre en valeur les changements dans la mémoire

### ISSUE THREAD

**Issue by JeanMax** [jon-finkel/corewar#4]
linked to #3 ?

**Comment by JeanMax** [comment]
il faudrait mettre en evidence le 1er pc / 1ere operation

**Comment by uael** [comment]
Si on save tout on peu faire un truc bien plus poussé hehe, mais je suis d'avis de prioriser une VM ultra stable et opti avant de l'envisager. Pareil #3

**Comment by JeanMax** [comment]
yep jsuis daccord, c'est secondaire
on essayait de lister tous les trucs qu'on voudra faire a un moment donné...

idéalement ça serait pas mal d'avoir un plan d'attaque un peu plus propre, c'est un peu le bordel pour la repartition des taches la

**Comment by uael** [comment]
On s'y colle demain?

**Comment by Freccia** [comment]
Done! #b6cce317323cc
