### ISSUE TITLE
Vm: Check command line options

### ISSUE THREAD

**Issue by JeanMax** [jon-finkel/corewar#6]
Verifier que toutes les options soient fonctionnelles:
* -d
* -n
* -c
* -v
* -g

**Comment by uael** [comment]
Ma prio 1 demain matin

**Comment by JeanMax** [comment]
nice!

-d ca devrait etre fait dans test-vm.sh
-g ça va etre galere

**Comment by uael** [comment]
Je pense surtout a -n qui est caraque

**Comment by uael** [comment]
Et les overflow

**Comment by uael** [comment]
done !
