### ISSUE TITLE
VM: write tests

### ISSUE THREAD

**Issue by JeanMax** [jon-finkel/corewar#7]
* tester les operations
* tester le parsing des arguments
* tester les differents flags

**Comment by uael** [comment]
Je commence demain aprem!

**Comment by uael** [comment]
Je pense a des -d et des diff sur la memoire avec l'executable de zaz

**Comment by JeanMax** [comment]
yes on pensait a ça, finalement on s'est orienté sur des tests unitaires en se disant que ça serait plus facile de faire des memcmp sur la map que de se manger des diffs: https://github.com/jon-finkel/corewar/commit/6d358711697669031c4a38b2472b4312356df127

le truc c'est qu'on va surement avoir des differences entre la vm de zaz et la notre, du coup les diff brute ca ptet pas etre tres pratique

**Comment by Freccia** [comment]
je pense qu'imprimer les registres des processus dans le gui compte comme test ;o)

**Comment by Freccia** [comment]
PS: les tests marchent (on as le meme comportement que la vm de zaz) !
Je close.
